/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
extern void LoadConfig_rawbot( void);
extern void ReloadConfig_rawbot( void);
extern void UnloadConfig_rawbot( void);
extern char IsrawbotLoaded( void);
extern void LoadConfig_Config1( void);
extern void UnloadConfig_Config1( void);
extern char IsConfig1Loaded( void);
extern void UnloadConfig_Total( void);
